### ISSUE TITLE
Pantalla Home principal

### ISSUE THREAD

**Issue by JCarri14** [assembler-school/apollofy-music-project#10]
**User Stories**

- [ ] Pantalla home básica #11 
- [ ] Sección “Playlists populares” en pantalla home #12
- [ ] Sección “Artistas populares” en pantalla home #13
- [ ] Sección “Playlists que sigo” en pantalla home #14
