### ISSUE TITLE
Gestión de la cuenta

### ISSUE THREAD

**Issue by JCarri14** [assembler-school/apollofy-music-project#15]
**User Stories**

- [ ] Visualización de información de usuario #16
- [ ] Edición de información de usuario #17
- [ ] Cambio de contraseña de usuario #18
