### ISSUE TITLE
Publicación, visualización y gestión de canciones

### ISSUE THREAD

**Issue by JCarri14** [assembler-school/apollofy-music-project#19]
**User Stories**

- [ ] Subida de canciones #20
- [ ] Visualización de “Mis canciones” #21
- [ ] Dar “Me gusta” a una canción #22
- [ ] Me gusta a una canción dentro del diálogo de información de canción #52 
- [ ] Opción de editar canción dentro de diálogo de información de canción #53
- [ ] Eliminar canción dentro del diálogo de información de canción #23
