### ISSUE TITLE
Publicación, visualización y gestión de playlists

### ISSUE THREAD

**Issue by JCarri14** [assembler-school/apollofy-music-project#32]
**User Stories**

- [ ] Listado de playlists #33 
- [ ] Orden manual en listado de playlists #34
- [ ] Creación de playlists #35
- [ ] Vista de playlists #36
- [ ] Seguir Playlist en Visualización de Playlists  #37 
- [ ] Cambio de privacidad en vista de Playlist #38 
- [ ] Añadir canciones dentro de Playlist desde vista Playlist #39 
- [ ] Menú “Opciones” dentro de Playlist #40
