### ISSUE TITLE
Visualización y gestión de usuarios/artistas

### ISSUE THREAD

**Issue by JCarri14** [assembler-school/apollofy-music-project#44]
**User Stories**

- [ ] Vista de usuario #45 
- [ ] Seguir a otros usuarios #46 
- [ ] Visualización de seguidores #47 
- [ ] Visualización de siguiendo #48
