### ISSUE TITLE
Registro y Autenticación

### ISSUE THREAD

**Issue by JCarri14** [assembler-school/apollofy-music-project#5]
**User Stories**
- [ ] Autentificación de Usuario #4 
- [ ] Guardado de credenciales #6
- [ ] Cierre de sesión de usuario #7
- [ ] Registro de Usuarios #8
- [ ] Recuperación de password #9
